In [167]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [168]:
import numpy as np
import matplotlib 
import matplotlib.pyplot as plt
import mpl_toolkits
#from mpl_toolkits.basemap import Basemap
import pandas as pd
import xarray as xr
import Nio
print (Nio.__version__)
import seaborn as seabornInstance 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from scipy import signal
%matplotlib inline

print("python version:")
import platform
print(platform.python_version())

1.5.5
python version:
3.7.3


In [169]:
precipdatpALLIN = xr.open_dataset('pALLIN.nc', decode_times=False)
precipdatpALLIN
time = pd.date_range('1874-05-31', freq='M', periods=1752)
precipALLIN = xr.Dataset({'data': ('data', precipdatpALLIN['precip']), 'time': time, 'foo': ('int', np.arange(1752))})
precipALLIN

<xarray.Dataset>
Dimensions:  (data: 1752, int: 1752, time: 1752)
Coordinates:
  * data     (data) float32 19.6 10.7 14.5 33.9 63.6 ... 168.7 52.1 8.0 7.0
  * time     (time) datetime64[ns] 1874-05-31 1874-06-30 ... 2020-04-30
Dimensions without coordinates: int
Data variables:
    foo      (int) int64 0 1 2 3 4 5 6 7 ... 1745 1746 1747 1748 1749 1750 1751

In [170]:
#precipitation

junenumber = []
for x in range(1752):
    y = (x + 1) % 12
    if (y == 6):
        junenumber.append(x)
#print precipALLIN.data[junenumber]

junedata = precipALLIN.sel(time = precipALLIN['time.month']==6, int = junenumber)
juneprecipALLIN = junedata.data[junenumber]
#print juneprecipALLIN

julynumber = []
for x in range(1752):
    y = (x + 1) % 12
    if (y == 7):
        julynumber.append(x)
#print precipALLIN.data[julynumber]

julydata = precipALLIN.sel(time = precipALLIN['time.month']==7, int = julynumber)
julyprecipALLIN = julydata.data[julynumber]
#print julyprecipALLIN

augustnumber = []
for x in range(1752):
    y = (x + 1) % 12
    if (y == 8):
        augustnumber.append(x)
#print precipALLIN.data[augustnumber]

augustdata = precipALLIN.sel(time = precipALLIN['time.month']==8, int = augustnumber)
augustprecipALLIN = augustdata.data[augustnumber]
#print augustprecipALLIN

septembernumber = []
for x in range(1752):
    y = (x + 1) % 12
    if (y == 9):
        septembernumber.append(x)
#print precipALLIN.data[septembernumber]

septemberdata = precipALLIN.sel(time = precipALLIN['time.month']==9, int = septembernumber)
septemberprecipALLIN = septemberdata.data[septembernumber]
#print septemberprecipALLIN

rainfallforAIRIfull = juneprecipALLIN.data + julyprecipALLIN.data + augustprecipALLIN.data + septemberprecipALLIN.data
rainfallforAIRIfull


array([ 848.7999 ,  913.6    ,  757.30005,  974.5    ,  929.7    ,
        777.69995,  604.     ,  976.1    ,  897.80005,  820.10004,
        861.3    ,  902.89996,  849.2999 ,  932.80005,  847.39996,
        874.39996,  899.3    ,  811.6    ,  930.60004,  905.5    ,
        792.4    ,  991.6    ,  954.9    ,  971.4    ,  823.60004,
        828.49994,  891.1    ,  884.6    ,  629.     ,  889.3    ,
        722.     ,  791.80005,  860.8    ,  750.3    ,  716.4    ,
        884.89996,  777.49994,  897.     ,  889.3    ,  934.89996,
        736.30005,  805.80005,  784.4    ,  898.     ,  780.6    ,
        950.6    , 1004.2    ,  650.8    ,  884.5    ,  719.     ,
        865.8    ,  869.     ,  823.     ,  862.6    ,  803.60004,
        902.6    ,  853.     ,  767.7    ,  821.1    ,  804.4    ,
        877.     ,  803.4    ,  975.8    ,  913.39996,  843.5    ,
        908.19995,  841.89996,  908.19995,  789.4    ,  853.1    ,
        728.30005,  957.69995,  868.2001 ,  920.3    ,  910.80

In [171]:
rainfalldata = []
for y in range(119):
    rainfalldata.append(rainfallforAIRIfull[y+26])

Ydata = ((rainfalldata - np.mean(rainfalldata))/np.std(rainfalldata)) 

In [172]:
#NAO Gibraltar-Stykkisholmur
NAOGS = xr.open_dataset('inao_1900_2019.nc', decode_times=False)
NAOGS
time = pd.date_range('1900-01-15', freq='M', periods=1440)
naoGS = xr.Dataset({'data': ('data', NAOGS['NAO']), 'time': time, 'foo': ('int', np.arange(1440))})
naoGS
# starts from 01/1900
NAOdata = naoGS.sel(time = slice('1900-01-31', '2019-12-31'))
NAOdata

<xarray.Dataset>
Dimensions:  (data: 1440, int: 1440, time: 1440)
Coordinates:
  * data     (data) float32 1.376 -2.358 -3.115 2.612 ... -1.106 -1.842 0.743
  * time     (time) datetime64[ns] 1900-01-31 1900-02-28 ... 2019-12-31
Dimensions without coordinates: int
Data variables:
    foo      (int) int64 0 1 2 3 4 5 6 7 ... 1433 1434 1435 1436 1437 1438 1439

In [173]:
junenumber = []
for x in range(1428):
    y = (x + 1) % 12
    if (y == 6):
        junenumber.append(x)

junedata = NAOdata.sel(time = NAOdata['time.month']==6, int = junenumber)
juneNAO = junedata.data[junenumber]

julynumber = []
for x in range(1428):
    y = (x + 1) % 12
    if (y == 7):
        julynumber.append(x)

julydata = NAOdata.sel(time = NAOdata['time.month']==7, int = julynumber)
julyNAO = julydata.data[julynumber]

augnumber = []
for x in range(1428):
    y = (x + 1) % 12
    if (y == 8):
        augnumber.append(x)

augdata = NAOdata.sel(time = NAOdata['time.month']==8, int = augnumber)
augNAO = augdata.data[augnumber]

septnumber = []
for x in range(1428):
    y = (x + 1) % 12
    if (y == 9):
        septnumber.append(x)

septdata = NAOdata.sel(time = NAOdata['time.month']==9, int = septnumber)
septNAO = septdata.data[septnumber]

fullNAOGS = juneNAO.data + julyNAO.data + augNAO.data + septNAO.data
fullNAOGS


array([-0.5120001 , -0.57299995, -6.187     ,  1.5169998 , -0.732     ,
       -1.558     , -1.3370001 ,  2.6750002 ,  2.5149999 ,  2.299     ,
       -3.556     ,  2.612     , -4.842     , -2.012     ,  0.85899997,
       -6.721     , -6.892     ,  2.676     ,  0.93099993,  3.2929997 ,
       -0.54700005, -4.09      ,  2.245     ,  5.4960003 , -0.18799984,
       -0.05400002,  0.4939999 , -1.931     , -3.4079998 ,  0.391     ,
       -1.9250001 , -5.625     , -1.0150001 ,  1.618     ,  0.33200002,
        3.362     ,  3.9520001 ,  0.783     ,  1.9120001 , -4.946     ,
       -3.204     , -0.25599998, -2.113     ,  1.141     , -4.426     ,
       -0.462     ,  7.81      ,  0.48399997,  1.4850001 , -2.866     ,
        1.623     ,  0.567     , -4.843     ,  1.1689999 ,  1.8340001 ,
       -0.1450001 , -2.044     , -2.137     , -0.89399993,  0.00899994,
       -1.83      ,  8.146     ,  1.609     , -2.4459996 , -1.3760002 ,
       -0.255     , -3.672     ,  3.3079998 , -1.96      ,  1.28

In [174]:
Xtrain = ((fullNAOGS - np.mean(fullNAOGS))/np.std(fullNAOGS)) 
Xdata = Xtrain.reshape(-1,1)
print(Xdata)

[[ 0.02635016]
 [ 0.0072226 ]
 [-1.7531432 ]
 [ 0.66257787]
 [-0.04263458]
 [-0.30164102]
 [-0.23234273]
 [ 1.0256886 ]
 [ 0.9755178 ]
 [ 0.9077874 ]
 [-0.92814815]
 [ 1.0059339 ]
 [-1.3313955 ]
 [-0.44400054]
 [ 0.4562507 ]
 [-1.9205881 ]
 [-1.9742081 ]
 [ 1.0260022 ]
 [ 0.47882754]
 [ 1.219473  ]
 [ 0.01537532]
 [-1.0955931 ]
 [ 0.8908547 ]
 [ 1.9102615 ]
 [ 0.12794599]
 [ 0.16996393]
 [ 0.3417987 ]
 [-0.41860157]
 [-0.88174015]
 [ 0.3095013 ]
 [-0.41672018]
 [-1.5769186 ]
 [-0.1313741 ]
 [ 0.69424814]
 [ 0.29100084]
 [ 1.2411093 ]
 [ 1.4261138 ]
 [ 0.4324196 ]
 [ 0.7864369 ]
 [-1.3640065 ]
 [-0.81777257]
 [ 0.10662337]
 [-0.47567078]
 [ 0.54467666]
 [-1.2009516 ]
 [ 0.04202854]
 [ 2.6358557 ]
 [ 0.338663  ]
 [ 0.6525438 ]
 [-0.7117868 ]
 [ 0.69581604]
 [ 0.3646891 ]
 [-1.331709  ]
 [ 0.5534565 ]
 [ 0.7619787 ]
 [ 0.14142929]
 [-0.45403466]
 [-0.48319644]
 [-0.09343243]
 [ 0.18971863]
 [-0.38693127]
 [ 2.7412145 ]
 [ 0.69142604]
 [-0.58008856]
 [-0.24457186]
 [ 0.10693694]
 [-0.96452

In [175]:
from sklearn.svm import SVC
from sklearn.model_selection import cross_validate

lmodel = LinearRegression()

clf = SVC(kernel='linear', C=1) #isn't working
cv_results = cross_validate(lmodel, Xdata, Ydata, cv=119, return_estimator=True) 

NAOGScoef = []

for model in cv_results['estimator']:
    NAOGScoef.append(model.coef_[0])
    print(model.coef_)
    
    

[0.10909723]
[0.10919607]
[0.07261093]
[0.10646971]
[0.10869914]
[0.10772609]
[0.10970295]
[0.12005295]
[0.12289163]
[0.10605737]
[0.10374818]
[0.10454082]
[0.11732561]
[0.11360833]
[0.11442406]
[0.10519109]
[0.10068658]
[0.10435861]
[0.11251031]
[0.09697077]
[0.10897255]
[0.08851497]
[0.10614006]
[0.13779582]
[0.10894177]
[0.10879888]
[0.1100357]
[0.11023529]
[0.10636611]
[0.10741851]
[0.10981873]
[0.0991343]
[0.10894821]
[0.11243339]
[0.10828719]
[0.11577695]
[0.09134962]
[0.10626742]
[0.10975735]
[0.12026117]
[0.10976123]
[0.10852301]
[0.10681689]
[0.10893288]
[0.09626833]
[0.10873336]
[0.1087984]
[0.10664096]
[0.10506012]
[0.11414945]
[0.10233486]
[0.10818983]
[0.11932676]
[0.10757674]
[0.1179544]
[0.10997216]
[0.11315154]
[0.11154874]
[0.11007009]
[0.10652754]
[0.10720013]
[0.10272258]
[0.10246146]
[0.10934547]
[0.11373523]
[0.10960141]
[0.11158761]
[0.10050473]
[0.10352349]
[0.11582296]
[0.1087545]
[0.10330054]
[0.10882235]
[0.10590372]
[0.10533772]
[0.1301781]
[0.11171835]
[0.10

/global/home/users/medhap02/.conda/envs/xarrayenv2/lib/python3.7/site-packages/sklearn/metrics/regression.py:543: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/global/home/users/medhap02/.conda/envs/xarrayenv2/lib/python3.7/site-packages/sklearn/metrics/regression.py:543: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/global/home/users/medhap02/.conda/envs/xarrayenv2/lib/python3.7/site-packages/sklearn/metrics/regression.py:543: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/global/home/users/medhap02/.conda/envs/xarrayenv2/lib/python3.7/site-packages/sklearn/metrics/regression.py:543: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/global/home/users/medhap02/.conda/e

In [176]:
#NAO
NAO = xr.open_dataset('icpc_nao_1950_2019.nc', decode_times=False)
NAO
time = pd.date_range('1950-01-01', freq='M', periods=840)
nao = xr.Dataset({'data': ('data', NAO['index']), 'time': time, 'foo': ('int', np.arange(840))})
nao
NAOdata = nao.sel(time = slice('1950-01-01', '2019-12-31'))
NAOdata
# starts from 01/1950

<xarray.Dataset>
Dimensions:  (data: 840, int: 840, time: 840)
Coordinates:
  * data     (data) float32 0.56 0.01 -0.78 0.65 -0.5 ... -0.01 -1.03 0.16 1.02
  * time     (time) datetime64[ns] 1950-01-31 1950-02-28 ... 2019-12-31
Dimensions without coordinates: int
Data variables:
    foo      (int) int64 0 1 2 3 4 5 6 7 8 ... 832 833 834 835 836 837 838 839

In [177]:
junenumber = []
for x in range(828):
    y = (x + 1) % 12
    if (y == 6):
        junenumber.append(x)

junedata = NAOdata.sel(time = NAOdata['time.month']==6, int = junenumber)
juneNAO = junedata.data[junenumber]

julynumber = []
for x in range(828):
    y = (x + 1) % 12
    if (y == 7):
        julynumber.append(x)

julydata = NAOdata.sel(time = NAOdata['time.month']==7, int = julynumber)
julyNAO = julydata.data[julynumber]

augnumber = []
for x in range(828):
    y = (x + 1) % 12
    if (y == 8):
        augnumber.append(x)

augdata = NAOdata.sel(time = NAOdata['time.month']==8, int = augnumber)
augNAO = augdata.data[augnumber]

septnumber = []
for x in range(828):
    y = (x + 1) % 12
    if (y == 9):
        septnumber.append(x)

septdata = NAOdata.sel(time = NAOdata['time.month']==9, int = septnumber)
septNAO = septdata.data[septnumber]

fullNAO = juneNAO.data + julyNAO.data + augNAO.data + septNAO.data
fullNAO


array([-0.7800001 , -1.55      , -1.03      ,  0.60999995, -3.36      ,
        2.69      , -1.82      , -3.8799999 , -4.82      ,  2.43      ,
       -0.91999996,  3.1999998 , -2.1200001 ,  0.07000005,  1.4699999 ,
        1.9100001 , -0.96000004,  4.94      , -2.83      ,  1.6400001 ,
        2.06      ,  1.39      ,  3.0000002 ,  0.9499999 , -0.56      ,
        2.2399998 ,  2.0499997 , -0.6700001 ,  1.89      ,  5.02      ,
       -2.68      , -0.96      ,  1.91      ,  3.53      ,  1.5       ,
       -0.35000002, -0.79      , -3.21      , -0.01999992,  3.0700002 ,
        3.15      ,  1.09      ,  1.3900001 , -3.8100002 ,  2.4       ,
        1.46      ,  2.07      ,  0.88000005, -4.84      ,  1.45      ,
       -1.28      , -0.82      ,  1.1599998 ,  0.33999997,  0.34999996,
        0.89      , -1.6999999 , -1.0199999 , -2.81      , -1.7699999 ,
       -3.2199998 , -3.6399999 , -5.3599997 ,  3.0300002 , -1.02      ,
       -4.49      , -3.3500001 , -0.34999996,  7.01      ], dtyp

In [178]:
Xtrain = ((fullNAO - np.mean(fullNAO))/np.std(fullNAO)) 
Xdata = Xtrain.reshape(-1,1)
print(Xdata)

[[-0.3107279 ]
 [-0.6094246 ]
 [-0.4077073 ]
 [ 0.22847798]
 [-1.311556  ]
 [ 1.0353472 ]
 [-0.7141625 ]
 [-1.5132732 ]
 [-1.8779162 ]
 [ 0.9344886 ]
 [-0.36503634]
 [ 1.2331853 ]
 [-0.83053786]
 [ 0.01900237]
 [ 0.56208736]
 [ 0.73277134]
 [-0.3805531 ]
 [ 1.9081625 ]
 [-1.1059595 ]
 [ 0.6280335 ]
 [ 0.79095894]
 [ 0.53105396]
 [ 1.1556019 ]
 [ 0.36037007]
 [-0.22538592]
 [ 0.8607841 ]
 [ 0.7870797 ]
 [-0.26805693]
 [ 0.7250129 ]
 [ 1.9391959 ]
 [-1.0477718 ]
 [-0.38055307]
 [ 0.7327712 ]
 [ 1.3611983 ]
 [ 0.5737249 ]
 [-0.14392318]
 [-0.31460705]
 [-1.2533684 ]
 [-0.01591023]
 [ 1.1827561 ]
 [ 1.2137895 ]
 [ 0.41467857]
 [ 0.531054  ]
 [-1.4861192 ]
 [ 0.9228511 ]
 [ 0.5582082 ]
 [ 0.79483813]
 [ 0.33321586]
 [-1.8856746 ]
 [ 0.5543291 ]
 [-0.5046868 ]
 [-0.32624456]
 [ 0.4418328 ]
 [ 0.12374017]
 [ 0.12761934]
 [ 0.33709502]
 [-0.6676123 ]
 [-0.4038281 ]
 [-1.0982012 ]
 [-0.6947665 ]
 [-1.2572474 ]
 [-1.4201729 ]
 [-2.0873916 ]
 [ 1.1672394 ]
 [-0.4038281 ]
 [-1.7499032 ]
 [-1.30767

In [179]:
from sklearn.svm import SVC
from sklearn.model_selection import cross_validate

lmodel = LinearRegression()

YdataNAO = []
for x in range (69):
    YdataNAO.append(Ydata[x+50])

clf = SVC(kernel='linear', C=1) #isn't working
cv_results = cross_validate(lmodel, Xdata, YdataNAO, cv=69, return_estimator=True) 

NAOcoef = []

for model in cv_results['estimator']:
    NAOcoef.append(model.coef_[0])
    print(model.coef_)

[-0.09370394]
[-0.0964326]
[-0.09506612]
[-0.10064287]
[-0.1268807]
[-0.09131175]
[-0.08977775]
[-0.09100238]
[-0.07411122]
[-0.12405653]
[-0.10298496]
[-0.11176719]
[-0.08518551]
[-0.09919379]
[-0.117446]
[-0.09556095]
[-0.09843969]
[-0.13319296]
[-0.12792982]
[-0.0881255]
[-0.10248777]
[-0.09117319]
[-0.09856782]
[-0.10559025]
[-0.09754047]
[-0.07073206]
[-0.11000945]
[-0.10387669]
[-0.11549494]
[-0.10987629]
[-0.09330244]
[-0.09494749]
[-0.08212606]
[-0.11178171]
[-0.10058198]
[-0.10200903]
[-0.09305872]
[-0.10310713]
[-0.09944378]
[-0.07966783]
[-0.06904358]
[-0.10819703]
[-0.10181361]
[-0.08472281]
[-0.09590195]
[-0.09679527]
[-0.10049341]
[-0.1061468]
[-0.11315294]
[-0.10040024]
[-0.0985866]
[-0.09844792]
[-0.09667334]
[-0.09795614]
[-0.09811549]
[-0.08753944]
[-0.09835253]
[-0.1067863]
[-0.10398576]
[-0.09221173]
[-0.07781074]
[-0.09214852]
[-0.16222262]
[-0.1101887]
[-0.0951611]
[-0.11642101]
[-0.07696003]
[-0.1019834]
[-0.04873391]


/global/home/users/medhap02/.conda/envs/xarrayenv2/lib/python3.7/site-packages/sklearn/metrics/regression.py:543: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/global/home/users/medhap02/.conda/envs/xarrayenv2/lib/python3.7/site-packages/sklearn/metrics/regression.py:543: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/global/home/users/medhap02/.conda/envs/xarrayenv2/lib/python3.7/site-packages/sklearn/metrics/regression.py:543: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/global/home/users/medhap02/.conda/envs/xarrayenv2/lib/python3.7/site-packages/sklearn/metrics/regression.py:543: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/global/home/users/medhap02/.conda/e

In [180]:
#Arctic Oscillation
AO = xr.open_dataset('icpc_ao_1950_2019.nc', decode_times=False)
AO
time = pd.date_range('1950-01-01', freq='M', periods=840)
ao = xr.Dataset({'data': ('data', AO['AO']), 'time': time, 'foo': ('int', np.arange(840))})
ao
AOdata = ao.sel(time = slice('1950-01-01', '2019-12-31'))
AOdata
# starts from 01/1950

<xarray.Dataset>
Dimensions:  (data: 840, int: 840, time: 840)
Coordinates:
  * data     (data) float32 -0.06031 0.62681 -0.0081275 ... -1.1934 0.41207
  * time     (time) datetime64[ns] 1950-01-31 1950-02-28 ... 2019-12-31
Dimensions without coordinates: int
Data variables:
    foo      (int) int64 0 1 2 3 4 5 6 7 8 ... 832 833 834 835 836 837 838 839

In [181]:
junenumber = []
for x in range(828):
    y = (x + 1) % 12
    if (y == 6):
        junenumber.append(x)

junedata = AOdata.sel(time = AOdata['time.month']==6, int = junenumber)
juneAO = junedata.data[junenumber]

julynumber = []
for x in range(828):
    y = (x + 1) % 12
    if (y == 7):
        julynumber.append(x)

julydata = AOdata.sel(time = AOdata['time.month']==7, int = julynumber)
julyAO = julydata.data[julynumber]

augnumber = []
for x in range(828):
    y = (x + 1) % 12
    if (y == 8):
        augnumber.append(x)

augdata = AOdata.sel(time = AOdata['time.month']==8, int = augnumber)
augAO = augdata.data[augnumber]

septnumber = []
for x in range(828):
    y = (x + 1) % 12
    if (y == 9):
        septnumber.append(x)

septdata = AOdata.sel(time = AOdata['time.month']==9, int = septnumber)
septAO = septdata.data[septnumber]

fullAO = juneAO.data + julyAO.data + augAO.data + septAO.data
fullAO

array([-0.75695   , -2.023027  , -0.471667  ,  1.102275  ,  0.25186998,
        1.18304   , -0.78862   , -2.265172  , -2.599888  , -0.95468396,
       -1.9536219 ,  1.556533  , -0.54335594, -1.4301    , -0.55801   ,
       -1.42475   , -0.515293  ,  0.74575996, -2.0959802 , -0.80346996,
        0.781151  , -0.2758    , -1.603583  ,  1.2283001 , -0.32671005,
        1.4304    , -0.18121994, -1.54361   , -0.42200902,  0.24159198,
        0.22671   , -1.16159   , -0.25537467,  1.70777   ,  0.07909051,
       -0.62315893, -0.32336354, -1.7257099 ,  1.211028  ,  2.46456   ,
       -0.38215   ,  0.38134   , -0.21578997, -1.78383   ,  2.700515  ,
       -0.33433998,  0.19601   , -0.93047   , -1.32197   ,  0.09191617,
        0.47542   , -0.23242602,  0.62910604,  0.159406  , -0.30159003,
        0.41504395,  1.51474   , -0.806298  , -0.97675204, -1.8857563 ,
       -0.558974  , -1.7272301 ,  0.28162897,  0.23090807, -1.2660199 ,
       -1.53439   ,  1.650988  ,  0.69348   ,  2.41221   ], dtyp

In [182]:
Xtrain = ((fullAO - np.mean(fullAO))/np.std(fullAO)) 
Xdata = Xtrain.reshape(-1,1)
print(Xdata)

[[-4.4358909e-01]
 [-1.5085561e+00]
 [-2.0362183e-01]
 [ 1.1203074e+00]
 [ 4.0498495e-01]
 [ 1.1882434e+00]
 [-4.7022843e-01]
 [-1.7122377e+00]
 [-1.9937856e+00]
 [-6.0991400e-01]
 [-1.4501756e+00]
 [ 1.5024089e+00]
 [-2.6392335e-01]
 [-1.0098126e+00]
 [-2.7624968e-01]
 [-1.0053124e+00]
 [-2.4031807e-01]
 [ 8.2042301e-01]
 [-1.5699210e+00]
 [-4.8271957e-01]
 [ 8.5019231e-01]
 [-3.8867310e-02]
 [-1.1557387e+00]
 [ 1.2263141e+00]
 [-8.1690557e-02]
 [ 1.3963114e+00]
 [ 4.0689182e-02]
 [-1.1052921e+00]
 [-1.6185178e-01]
 [ 3.9633957e-01]
 [ 3.8382152e-01]
 [-7.8395402e-01]
 [-2.1686450e-02]
 [ 1.6296226e+00]
 [ 2.5965062e-01]
 [-3.3105004e-01]
 [-7.8875631e-02]
 [-1.2584664e+00]
 [ 1.2117856e+00]
 [ 2.2662003e+00]
 [-1.2832415e-01]
 [ 5.1388931e-01]
 [ 1.1610418e-02]
 [-1.3073545e+00]
 [ 2.4646752e+00]
 [-8.8108517e-02]
 [ 3.5799804e-01]
 [-5.8954626e-01]
 [-9.1885847e-01]
 [ 2.7043900e-01]
 [ 5.9302515e-01]
 [-2.3830747e-03]
 [ 7.2229898e-01]
 [ 3.2720840e-01]
 [-6.0560729e-02]
 [ 5.42239

In [183]:
from sklearn.svm import SVC
from sklearn.model_selection import cross_validate

lmodel = LinearRegression()

YdataAO = []
for x in range (69):
    YdataAO.append(Ydata[x+50])

clf = SVC(kernel='linear', C=1) #isn't working
cv_results = cross_validate(lmodel, Xdata, YdataAO, cv=69, return_estimator=True) 

AOcoef = []

for model in cv_results['estimator']:
    AOcoef.append(model.coef_[0])
    print(model.coef_)

[-0.16073364]
[-0.165689]
[-0.1662309]
[-0.1782693]
[-0.16114764]
[-0.16094285]
[-0.16218928]
[-0.16257256]
[-0.14613199]
[-0.1539763]
[-0.18834855]
[-0.18677108]
[-0.16375102]
[-0.17157026]
[-0.1597964]
[-0.17697991]
[-0.16783944]
[-0.18165778]
[-0.21356085]
[-0.17783235]
[-0.17266254]
[-0.16893259]
[-0.17431161]
[-0.1936339]
[-0.16769965]
[-0.12444214]
[-0.16882409]
[-0.19054222]
[-0.16493978]
[-0.1696441]
[-0.17139906]
[-0.16057499]
[-0.16883922]
[-0.18702632]
[-0.16888301]
[-0.17497098]
[-0.16675332]
[-0.17388839]
[-0.15355909]
[-0.13817224]
[-0.17170191]
[-0.17981446]
[-0.16836141]
[-0.15710017]
[-0.17161135]
[-0.16878314]
[-0.16879073]
[-0.15714335]
[-0.17439145]
[-0.16885608]
[-0.17035617]
[-0.16830666]
[-0.16498478]
[-0.16520967]
[-0.16885115]
[-0.14995977]
[-0.17721674]
[-0.17772637]
[-0.17098631]
[-0.15747032]
[-0.16338418]
[-0.16344285]
[-0.15790224]
[-0.17160389]
[-0.16088624]
[-0.17899303]
[-0.20511274]
[-0.15487108]
[-0.13222876]


/global/home/users/medhap02/.conda/envs/xarrayenv2/lib/python3.7/site-packages/sklearn/metrics/regression.py:543: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/global/home/users/medhap02/.conda/envs/xarrayenv2/lib/python3.7/site-packages/sklearn/metrics/regression.py:543: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/global/home/users/medhap02/.conda/envs/xarrayenv2/lib/python3.7/site-packages/sklearn/metrics/regression.py:543: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/global/home/users/medhap02/.conda/envs/xarrayenv2/lib/python3.7/site-packages/sklearn/metrics/regression.py:543: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/global/home/users/medhap02/.conda/e

In [184]:
#Atlantic Multidecadal Oscillation derived from HadSST
AMO = xr.open_dataset('data/iamo_hadsst_1900_2019.nc', decode_times=False)
AMO
time = pd.date_range('1900-01-15', freq='M', periods=1428)
amo = xr.Dataset({'data': ('data', AMO['AMO']), 'time': time, 'foo': ('int', np.arange(1428))})
amo
# starts from 01/1900
AMOdata = amo.sel(time = slice('1900-01-15', '2019-12-31'))
AMOdata

<xarray.Dataset>
Dimensions:  (data: 1428, int: 1428, time: 1428)
Coordinates:
  * data     (data) float32 0.1547023 -0.01673885 ... -0.2677419 -0.153994
  * time     (time) datetime64[ns] 1900-01-31 1900-02-28 ... 2018-12-31
Dimensions without coordinates: int
Data variables:
    foo      (int) int64 0 1 2 3 4 5 6 7 ... 1421 1422 1423 1424 1425 1426 1427

In [185]:
junenumber = []
for x in range(1428):
    y = (x + 1) % 12
    if (y == 6):
        junenumber.append(x)

junedata = AMOdata.sel(time = AMOdata['time.month']==6, int = junenumber)
juneAMO = junedata.data[junenumber]

julynumber = []
for x in range(1428):
    y = (x + 1) % 12
    if (y == 7):
        julynumber.append(x)

julydata = AMOdata.sel(time = AMOdata['time.month']==7, int = julynumber)
julyAMO = julydata.data[julynumber]

augnumber = []
for x in range(1428):
    y = (x + 1) % 12
    if (y == 8):
        augnumber.append(x)

augdata = AMOdata.sel(time = AMOdata['time.month']==8, int = augnumber)
augAMO = augdata.data[augnumber]

septnumber = []
for x in range(1428):
    y = (x + 1) % 12
    if (y == 9):
        septnumber.append(x)

septdata = AMOdata.sel(time = AMOdata['time.month']==9, int = septnumber)
septAMO = septdata.data[septnumber]

fullAMO = juneAMO.data + julyAMO.data + augAMO.data + septAMO.data
fullAMO

array([-0.14385988,  0.6262229 , -1.477731  , -2.1588356 , -0.9679667 ,
       -1.0732203 ,  0.03771919, -0.45858228,  1.6035507 , -0.1217716 ,
        0.13798746,  1.7855619 , -1.0500519 , -1.1596768 , -1.4187768 ,
       -0.12088868,  0.50556475, -0.6964272 , -1.3159252 , -0.32996646,
       -1.0975301 , -0.31681532, -0.70634115, -0.8176375 , -0.6206552 ,
       -0.23233415, -0.8063017 ,  0.05806363,  0.7163703 ,  0.06535858,
        0.8099657 ,  0.35838795,  1.8078246 ,  1.4957134 ,  1.0966821 ,
        0.33002326,  0.41918963,  2.3744204 ,  1.0442846 ,  1.0897872 ,
       -0.01431129, -0.4844169 ,  1.7599173 ,  0.4903618 ,  0.4605748 ,
        0.6444931 ,  0.21319853, -0.75442594, -0.3267653 ,  1.0112559 ,
       -0.08183601,  0.98844725,  1.8814938 ,  0.31074122,  0.29296312,
        1.8759041 , -0.03802199, -0.47785255, -0.6266049 , -0.8564555 ,
        0.29513288, -0.12024304, -1.2170275 , -2.0107946 , -0.49311978,
       -0.81463337, -1.2194946 , -0.17642555, -1.5079349 , -1.79

In [186]:
Xtrain = ((fullAMO - np.mean(fullAMO))/np.std(fullAMO)) 
Xdata = Xtrain.reshape(-1,1)
print(Xdata)

[[-0.0112439 ]
 [ 0.79093295]
 [-1.4007056 ]
 [-2.1101959 ]
 [-0.8696963 ]
 [-0.97933644]
 [ 0.17790268]
 [-0.33908272]
 [ 1.8089919 ]
 [ 0.01176493]
 [ 0.28234977]
 [ 1.9985887 ]
 [-0.9552025 ]
 [-1.0693961 ]
 [-1.3392944 ]
 [ 0.01268465]
 [ 0.66524625]
 [-0.58684015]
 [-1.2321564 ]
 [-0.20510668]
 [-1.0046594 ]
 [-0.19140746]
 [-0.59716725]
 [-0.713102  ]
 [-0.5079102 ]
 [-0.10340544]
 [-0.70129377]
 [ 0.199095  ]
 [ 0.8848373 ]
 [ 0.20669398]
 [ 0.9823335 ]
 [ 0.51193565]
 [ 2.0217793 ]
 [ 1.6966604 ]
 [ 1.2809991 ]
 [ 0.48238888]
 [ 0.5752713 ]
 [ 2.6119888 ]
 [ 1.2264178 ]
 [ 1.2738168 ]
 [ 0.12370377]
 [-0.36599404]
 [ 1.9718753 ]
 [ 0.6494097 ]
 [ 0.61838126]
 [ 0.8099646 ]
 [ 0.36069533]
 [-0.647256  ]
 [-0.20177211]
 [ 1.1920125 ]
 [ 0.05336489]
 [ 1.1682534 ]
 [ 2.0985188 ]
 [ 0.46230322]
 [ 0.4437842 ]
 [ 2.0926962 ]
 [ 0.0990049 ]
 [-0.35915607]
 [-0.5141079 ]
 [-0.7535378 ]
 [ 0.44604436]
 [ 0.0133572 ]
 [-1.129137  ]
 [-1.9559853 ]
 [-0.3750596 ]
 [-0.7099726 ]
 [-1.13170

In [187]:
from sklearn.svm import SVC
from sklearn.model_selection import cross_validate

lmodel = LinearRegression()

clf = SVC(kernel='linear', C=1) #isn't working
cv_results = cross_validate(lmodel, Xdata, Ydata, cv=119, return_estimator=True) 

AMOcoef = []

for model in cv_results['estimator']:
    AMOcoef.append(model.coef_[0])
    print(model.coef_)
    

[-0.03929174]
[-0.04295749]
[-0.0712988]
[-0.03045385]
[-0.05046965]
[-0.04485412]
[-0.03968403]
[-0.04261393]
[-0.01629728]
[-0.03939798]
[-0.0374755]
[-0.05220587]
[-0.03507256]
[-0.02953777]
[-0.05484448]
[-0.03929892]
[-0.03548188]
[-0.03613574]
[-0.04784948]
[-0.03709356]
[-0.02291074]
[-0.04313645]
[-0.03691111]
[-0.04863094]
[-0.03823907]
[-0.03907418]
[-0.0409539]
[-0.03976237]
[-0.03601209]
[-0.04062786]
[-0.04069417]
[-0.03547133]
[-0.03606229]
[-0.03344925]
[-0.0444441]
[-0.03746269]
[-0.04732649]
[-0.06181462]
[-0.03992614]
[-0.04854875]
[-0.0393391]
[-0.03693723]
[-0.02947892]
[-0.0401679]
[-0.03217319]
[-0.04916312]
[-0.04032696]
[-0.03432881]
[-0.03795472]
[-0.04734024]
[-0.039909]
[-0.04356388]
[-0.05446954]
[-0.04103319]
[-0.03466015]
[-0.02969752]
[-0.04016328]
[-0.03782684]
[-0.03483039]
[-0.02863459]
[-0.0369163]
[-0.03941091]
[-0.02792271]
[-0.04133912]
[-0.03256076]
[-0.04194232]
[-0.03802231]
[-0.03897902]
[-0.06002624]
[-0.05921172]
[-0.03777427]
[-0.04785016]
[

/global/home/users/medhap02/.conda/envs/xarrayenv2/lib/python3.7/site-packages/sklearn/metrics/regression.py:543: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/global/home/users/medhap02/.conda/envs/xarrayenv2/lib/python3.7/site-packages/sklearn/metrics/regression.py:543: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/global/home/users/medhap02/.conda/envs/xarrayenv2/lib/python3.7/site-packages/sklearn/metrics/regression.py:543: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/global/home/users/medhap02/.conda/envs/xarrayenv2/lib/python3.7/site-packages/sklearn/metrics/regression.py:543: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/global/home/users/medhap02/.conda/e

In [188]:
NAOGSregressionstd = np.std(NAOGScoef)
NAOGSregressionmean = np.mean(NAOGScoef)
NAOGSmodel = []
NAOGSmodel.append(NAOGSregressionstd)
NAOGSmodel.append(NAOGSregressionmean)

NAOregressionstd = np.std(NAOcoef)
NAOregressionmean = np.mean(NAOcoef)
NAOmodel = []
NAOmodel.append(NAOregressionstd)
NAOmodel.append(NAOregressionmean)

AOregressionstd = np.std(AOcoef)
AOregressionmean = np.mean(AOcoef)
AOmodel = []
AOmodel.append(AOregressionstd)
AOmodel.append(AOregressionmean)

AMOregressionstd = np.std(AMOcoef)
AMOregressionmean = np.mean(AMOcoef)
AMOmodel = []
AMOmodel.append(AMOregressionstd)
AMOmodel.append(AMOregressionmean)

pd.DataFrame.from_items([('NAO GS(1900 - 2018)', NAOGSmodel), ('NAO(1950 - 2018)', NAOmodel), ('AO(1950 - 2018)', AOmodel), ('AMO(1900 - 2018)', AMOmodel)], orient='index', columns=['Standard Deviation', 'Mean'])

/global/home/users/medhap02/.conda/envs/xarrayenv2/lib/python3.7/site-packages/ipykernel_launcher.py:25: FutureWarning: from_items is deprecated. Please use DataFrame.from_dict(dict(items), ...) instead. DataFrame.from_dict(OrderedDict(items)) may be used to preserve the key order.


Standard Deviation      Mean
NAO GS(1900 - 2018)            0.008839  0.109216
NAO(1950 - 2018)               0.015793 -0.099205
AO(1950 - 2018)                0.013885 -0.168286
AMO(1900 - 2018)               0.008034 -0.039354

In [ ]:
# Copyright (c) 2020 Medha Palavalli.