In [95]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [96]:
import numpy as np
import scipy as sp
import sklearn as sk
import cartopy as cp
import xarray as xr
import pandas as pd
import cftime
import dateutil
import dask
#Use the 2 lines below if the notebook has a dark theme (to make labelling visible):
from jupyterthemes import jtplot
jtplot.style(theme='chesterish', context='notebook', ticks=True, grid=False)
import matplotlib.pyplot as plt
#The following code resets the default plot size so you don't have to fiddle with figsize every time"
fig_size = plt.rcParams["figure.figsize"]
fig_size[0] = 16
fig_size[1] = 8
plt.rcParams["figure.figsize"] = fig_size

In [97]:
#Need the following line to avoid hdf5 issues that prevent opening thee file
# https://stackoverflow.com/questions/49317927/errno-101-netcdf-hdf-error-when-opening-netcdf-file
%env HDF5_USE_FILE_LOCKING=FALSE

env: HDF5_USE_FILE_LOCKING=FALSE


In [98]:
#Load AIRI data 
from netCDF4 import Dataset
from datetime import datetime, timedelta
from netCDF4 import num2date, date2num
dataset_file = "pALLIN.nc"
airi_dat = xr.open_dataset(dataset_file, decode_times=False)
units, reference_date = airi_dat.time.attrs['units'].split('since')
airi_dat['time'] = pd.date_range(start=reference_date, periods=airi_dat.sizes['time'], freq='MS')
#This file's calendar isn't recognized when using xr.open_dataset. The above workaround is from: 
#https://stackoverflow.com/questions/55648630/how-to-decode-the-time-variable-while-using-xarray-to-load-a-netcdf-file
# "M" means "month end frequency" (see https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases)

In [99]:
airi_dat

<xarray.Dataset>
Dimensions:  (time: 1752)
Coordinates:
  * time     (time) datetime64[ns] 1871-02-01 1871-03-01 ... 2017-01-01
Data variables:
    precip   (time) float32 ...
Attributes:
    title:        
    description:  All-India Rainfall
    scripturl01:  https://climexp.knmi.nl/getindices.cgi?STATION=All-India_Ra...
    comment:      
    institution:  KNMI Climate Explorer
    scripturl02:  https://climexp.knmi.nl/dat2nc.cgi?id=$id&station=All-India...
    history:       2020-04-02  2:43:20 bin/dat2nc data/pALLIN.dat p All-India...
    Conventions:  CF-1.0

In [100]:
precip = airi_dat['precip']

In [101]:
#Load SST data
dataset_url = "https://psl.noaa.gov/thredds/dodsC/Datasets/noaa.ersst.v5/sst.mnmean.nc"
sst_dat = xr.open_dataset(dataset_url)
sst = sst_dat['sst']

In [102]:
#Slice SST data to the same duration as precip and calculate monthly anomalies
sst_subset = sst.sel(time=slice('1871-01-30','2017-01-01'))
sst_clim = sst_subset.groupby('time.month').mean('time')
sst_anomfull = sst_subset.groupby("time.month")-sst_clim
sst_anomfull

/global/home/users/medhap02/.conda/envs/xarrayenv2/lib/python3.7/site-packages/xarray/core/nanops.py:160: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)


<xarray.DataArray 'sst' (time: 1752, lat: 89, lon: 180)>
array([[[1.788139e-06, 1.788139e-06, ..., 1.788139e-06, 1.788139e-06],
        [1.788139e-06, 1.788139e-06, ..., 1.788139e-06, 1.788139e-06],
        ...,
        [         nan,          nan, ...,          nan,          nan],
        [         nan,          nan, ...,          nan,          nan]],

       [[1.788139e-06, 1.788139e-06, ..., 1.788139e-06, 1.788139e-06],
        [1.788139e-06, 1.788139e-06, ..., 1.788139e-06, 1.788139e-06],
        ...,
        [         nan,          nan, ...,          nan,          nan],
        [         nan,          nan, ...,          nan,          nan]],

       ...,

       [[3.152323e-02, 2.609873e-02, ..., 2.140296e-02, 3.102016e-02],
        [2.697122e-02, 1.542413e-02, ..., 1.046002e-02, 2.427316e-02],
        ...,
        [         nan,          nan, ...,          nan,          nan],
        [         nan,          nan, ...,          nan,          nan]],

       [[1.788139e-06, 1.788139e-

In [103]:
sst_subset1 = sst_anomfull.sel(time=slice('1900-01-01','1901-12-31'))
sst_subset2 = sst_anomfull.sel(time=slice('1903-01-01','1906-12-31'))
sst_subset3 = sst_anomfull.sel(time=slice('1908-01-01','1911-12-31'))
sst_subset4 = sst_anomfull.sel(time=slice('1913-01-01','1913-12-31'))
sst_subset5 = sst_anomfull.sel(time=slice('1915-01-01','1918-12-31'))
sst_subset6 = sst_anomfull.sel(time=slice('1920-01-01','1921-12-31'))
sst_subset7 = sst_anomfull.sel(time=slice('1923-01-01','1927-12-31'))
sst_subset8 = sst_anomfull.sel(time=slice('1929-01-01','1931-12-31'))
sst_subset9 = sst_anomfull.sel(time=slice('1934-01-01','1939-12-31'))
sst_subset10 = sst_anomfull.sel(time=slice('1941-01-01','1948-12-31'))
sst_subset11 = sst_anomfull.sel(time=slice('1951-01-01','1955-12-31'))
sst_subset12 = sst_anomfull.sel(time=slice('1957-01-01','1958-12-31'))
sst_subset13 = sst_anomfull.sel(time=slice('1960-01-01','1962-12-31'))
sst_subset13 = sst_anomfull.sel(time=slice('1964-01-01','1965-12-31'))
sst_subset14 = sst_anomfull.sel(time=slice('1967-01-01','1971-12-31'))
sst_subset15 = sst_anomfull.sel(time=slice('1973-01-01','1976-12-31'))
sst_subset16 = sst_anomfull.sel(time=slice('1978-01-01','1979-12-31'))
sst_subset17 = sst_anomfull.sel(time=slice('1981-01-01','1982-12-31'))
sst_subset18 = sst_anomfull.sel(time=slice('1984-01-01','1991-12-31'))
sst_subset19 = sst_anomfull.sel(time=slice('1993-01-01','1998-12-31'))
sst_subset20 = sst_anomfull.sel(time=slice('2000-01-01','2002-12-31'))
sst_subset21 = sst_anomfull.sel(time=slice('2004-01-01','2006-12-31'))
sst_subset22 = sst_anomfull.sel(time=slice('2008-01-01','2010-12-31'))
sst_subset23 = sst_anomfull.sel(time=slice('2012-01-01','2015-12-31'))

sst_anomtemp = xr.merge([sst_subset1, sst_subset2, sst_subset3, sst_subset4, sst_subset5, 
                   sst_subset6, sst_subset7, sst_subset8, sst_subset9, sst_subset10, 
                   sst_subset11, sst_subset12, sst_subset13, sst_subset14, sst_subset15, 
                   sst_subset16, sst_subset17, sst_subset18, sst_subset19, sst_subset20, 
                   sst_subset21, sst_subset22, sst_subset23])
#sst_anom = xr.Dataset.to_array(sst_anomtemp).drop('variable')
print(sst_anomtemp)
sst_anom = sst_anomtemp['sst']
#1902, 1907, 1912, 1914, 1919, 1922, 1928, 1932, 1933, 1940
#1949, 1950, 1956, 1959, 1963, 1966, 1972, 1977, 1980, 1983
#1992, 1999, 2003, 2007, 2011

<xarray.Dataset>
Dimensions:  (lat: 89, lon: 180, time: 1056)
Coordinates:
  * time     (time) datetime64[ns] 1900-01-01 1900-02-01 ... 2015-12-01
  * lat      (lat) float32 88.0 86.0 84.0 82.0 80.0 ... -82.0 -84.0 -86.0 -88.0
  * lon      (lon) float32 0.0 2.0 4.0 6.0 8.0 ... 350.0 352.0 354.0 356.0 358.0
    month    (time) float64 1.0 2.0 3.0 4.0 5.0 6.0 ... 8.0 9.0 10.0 11.0 12.0
Data variables:
    sst      (time, lat, lon) float32 1.7881393e-06 1.7881393e-06 ... nan nan


In [173]:
#Load SLP data
dataset_url = "/global/scratch/medhap02/prmsl.mon.mean.nc"
slp_dat = xr.open_dataset(dataset_url)
slp = slp_dat['prmsl']

In [175]:
#Slice SLP data to the same duration as precip and calculate monthly anomalies
slp_subset = slp.sel(time=slice('1871-01-01','2015-12-31'))
slp_clim = slp_subset.groupby('time.month').mean('time')
slp_anomfull = slp_subset.groupby("time.month")-slp_clim
slp_anomfull

<xarray.DataArray 'prmsl' (time: 1740, lat: 181, lon: 360)>
array([[[  114.765625,   114.765625, ...,   114.765625,   114.765625],
        [   94.78125 ,    94.46875 , ...,    95.359375,    95.03125 ],
        ...,
        [  293.65625 ,   293.95312 , ...,   293.20312 ,   293.4297  ],
        [  288.66406 ,   288.66406 , ...,   288.66406 ,   288.66406 ]],

       [[   75.84375 ,    75.84375 , ...,    75.84375 ,    75.84375 ],
        [   67.66406 ,    68.02344 , ...,    66.85156 ,    67.24219 ],
        ...,
        [  587.2969  ,   587.52344 , ...,   586.9219  ,   587.0781  ],
        [  581.14844 ,   581.14844 , ...,   581.14844 ,   581.14844 ]],

       ...,

       [[ -876.5703  ,  -876.5703  , ...,  -876.5703  ,  -876.5703  ],
        [ -937.10156 ,  -936.8594  , ...,  -937.625   ,  -937.3906  ],
        ...,
        [-1008.4375  , -1008.8906  , ..., -1007.5625  , -1007.9922  ],
        [-1047.0938  , -1047.0938  , ..., -1047.0938  , -1047.0938  ]],

       [[ -525.5     ,  -525.5

In [176]:
slp_subset1 = slp_anomfull.sel(time=slice('1900-01-01','1901-12-31'))
slp_subset2 = slp_anomfull.sel(time=slice('1903-01-01','1906-12-31'))
slp_subset3 = slp_anomfull.sel(time=slice('1908-01-01','1911-12-31'))
slp_subset4 = slp_anomfull.sel(time=slice('1913-01-01','1913-12-31'))
slp_subset5 = slp_anomfull.sel(time=slice('1915-01-01','1918-12-31'))
slp_subset6 = slp_anomfull.sel(time=slice('1920-01-01','1921-12-31'))
slp_subset7 = slp_anomfull.sel(time=slice('1923-01-01','1927-12-31'))
slp_subset8 = slp_anomfull.sel(time=slice('1929-01-01','1931-12-31'))
slp_subset9 = slp_anomfull.sel(time=slice('1934-01-01','1939-12-31'))
slp_subset10 = slp_anomfull.sel(time=slice('1941-01-01','1948-12-31'))
slp_subset11 = slp_anomfull.sel(time=slice('1951-01-01','1955-12-31'))
slp_subset12 = slp_anomfull.sel(time=slice('1957-01-01','1958-12-31'))
slp_subset13 = slp_anomfull.sel(time=slice('1960-01-01','1962-12-31'))
slp_subset13 = slp_anomfull.sel(time=slice('1964-01-01','1965-12-31'))
slp_subset14 = slp_anomfull.sel(time=slice('1967-01-01','1971-12-31'))
slp_subset15 = slp_anomfull.sel(time=slice('1973-01-01','1976-12-31'))
slp_subset16 = slp_anomfull.sel(time=slice('1978-01-01','1979-12-31'))
slp_subset17 = slp_anomfull.sel(time=slice('1981-01-01','1982-12-31'))
slp_subset18 = slp_anomfull.sel(time=slice('1984-01-01','1991-12-31'))
slp_subset19 = slp_anomfull.sel(time=slice('1993-01-01','1998-12-31'))
slp_subset20 = slp_anomfull.sel(time=slice('2000-01-01','2002-12-31'))
slp_subset21 = slp_anomfull.sel(time=slice('2004-01-01','2006-12-31'))
slp_subset22 = slp_anomfull.sel(time=slice('2008-01-01','2010-12-31'))
slp_subset23 = slp_anomfull.sel(time=slice('2012-01-01','2015-12-31'))

slp_anomtemp = xr.merge([slp_subset1, slp_subset2, slp_subset3, slp_subset4, slp_subset5, 
                   slp_subset6, slp_subset7, slp_subset8, slp_subset9, slp_subset10, 
                   slp_subset11, slp_subset12, slp_subset13, slp_subset14, slp_subset15, 
                   slp_subset16, slp_subset17, slp_subset18, slp_subset19, slp_subset20, 
                   slp_subset21, slp_subset22, slp_subset23])
#slp_anom = xr.Dataset.to_array(slp_anomtemp).drop('variable')
print(slp_anomtemp)
slp_anom = slp_anomtemp['prmsl']
#1902, 1907, 1912, 1914, 1919, 1922, 1928, 1932, 1933, 1940
#1949, 1950, 1956, 1959, 1963, 1966, 1972, 1977, 1980, 1983
#1992, 1999, 2003, 2007, 2011

<xarray.Dataset>
Dimensions:  (lat: 181, lon: 360, time: 1056)
Coordinates:
  * time     (time) datetime64[ns] 1900-01-01 1900-02-01 ... 2015-12-01
  * lat      (lat) float32 -90.0 -89.0 -88.0 -87.0 -86.0 ... 87.0 88.0 89.0 90.0
  * lon      (lon) float32 0.0 1.0 2.0 3.0 4.0 ... 355.0 356.0 357.0 358.0 359.0
    month    (time) float64 1.0 2.0 3.0 4.0 5.0 6.0 ... 8.0 9.0 10.0 11.0 12.0
Data variables:
    prmsl    (time, lat, lon) float32 24.570312 24.570312 ... -411.48438


In [104]:
#Get precip anomalies
precip_clim = precip.groupby("time.month").mean("time")
precip_anomfull = precip.groupby("time.month") - precip_clim

In [105]:
precip_subset1 = precip_anomfull.sel(time=slice('1900-01-01','1901-12-31'))
precip_subset2 = precip_anomfull.sel(time=slice('1903-01-01','1906-12-31'))
precip_subset3 = precip_anomfull.sel(time=slice('1908-01-01','1911-12-31'))
precip_subset4 = precip_anomfull.sel(time=slice('1913-01-01','1913-12-31'))
precip_subset5 = precip_anomfull.sel(time=slice('1915-01-01','1918-12-31'))
precip_subset6 = precip_anomfull.sel(time=slice('1920-01-01','1921-12-31'))
precip_subset7 = precip_anomfull.sel(time=slice('1923-01-01','1927-12-31'))
precip_subset8 = precip_anomfull.sel(time=slice('1929-01-01','1931-12-31'))
precip_subset9 = precip_anomfull.sel(time=slice('1934-01-01','1939-12-31'))
precip_subset10 = precip_anomfull.sel(time=slice('1941-01-01','1948-12-31'))
precip_subset11 = precip_anomfull.sel(time=slice('1951-01-01','1955-12-31'))
precip_subset12 = precip_anomfull.sel(time=slice('1957-01-01','1958-12-31'))
precip_subset13 = precip_anomfull.sel(time=slice('1960-01-01','1962-12-31'))
precip_subset13 = precip_anomfull.sel(time=slice('1964-01-01','1965-12-31'))
precip_subset14 = precip_anomfull.sel(time=slice('1967-01-01','1971-12-31'))
precip_subset15 = precip_anomfull.sel(time=slice('1973-01-01','1976-12-31'))
precip_subset16 = precip_anomfull.sel(time=slice('1978-01-01','1979-12-31'))
precip_subset17 = precip_anomfull.sel(time=slice('1981-01-01','1982-12-31'))
precip_subset18 = precip_anomfull.sel(time=slice('1984-01-01','1991-12-31'))
precip_subset19 = precip_anomfull.sel(time=slice('1993-01-01','1998-12-31'))
precip_subset20 = precip_anomfull.sel(time=slice('2000-01-01','2002-12-31'))
precip_subset21 = precip_anomfull.sel(time=slice('2004-01-01','2006-12-31'))
precip_subset22 = precip_anomfull.sel(time=slice('2008-01-01','2010-12-31'))
precip_subset23 = precip_anomfull.sel(time=slice('2012-01-01','2015-12-31'))

precip_anom = xr.merge([precip_subset1, precip_subset2, precip_subset3, precip_subset4, precip_subset5, 
                   precip_subset6, precip_subset7, precip_subset8, precip_subset9, precip_subset10, 
                   precip_subset11, precip_subset12, precip_subset13, precip_subset14, precip_subset15, 
                   precip_subset16, precip_subset17, precip_subset18, precip_subset19, precip_subset20, 
                   precip_subset21, precip_subset22, precip_subset23])
precip_anomtemp = xr.Dataset.to_array(precip_anom)
precip_anom = precip_anom['precip']
print(precip_anom)
#1902, 1907, 1912, 1914, 1919, 1922, 1928, 1932, 1933, 1940
#1949, 1950, 1956, 1959, 1963, 1966, 1972, 1977, 1980, 1983
#1992, 1999, 2003, 2007, 2011

<xarray.DataArray 'precip' (time: 1056)>
array([ -9.166439,   4.535616,  -5.745206, ..., -44.439735, -40.930824,
        13.444523], dtype=float32)
Coordinates:
  * time     (time) datetime64[ns] 1900-01-01 1900-02-01 ... 2015-12-01
    month    (time) float64 1.0 2.0 3.0 4.0 5.0 6.0 ... 8.0 9.0 10.0 11.0 12.0


In [119]:
junes = np.arange(5,1056,12)
julys = np.arange(6,1056,12) #1752 instead of 1068
augusts = np.arange(7,1056, 12)
septembers = np.arange(8,1056,12)
precipa_june = precip_anom[junes]
precipa_july = precip_anom[julys]
precipa_august = precip_anom[augusts]
precipa_september = precip_anom[septembers]

precipa_july.time.data = precipa_june.time.data
precipa_august.time.data = precipa_june.time.data
precipa_september.time.data = precipa_june.time.data

precipa_jjas = (precipa_june + precipa_july + precipa_august + precipa_september)
precipa_jjas.time.data = EPT.time.data

In [106]:
def covariance(x, y, dims=None):
    return xr.dot(x - x.mean(dims), y - y.mean(dims), dims=dims) / x.count(dims)

def correlation(x, y, dims=None):
    return covariance(x, y, dims) / (x.std(dims) * y.std(dims))

# EPT

In [150]:
#EPT original

#DSST1
latrange1 = sst_anom.sel(lat = slice(5, -20)).lat
weights1 = np.cos(latrange1*np.pi/180)

marchdata1 = sst_anom.sel(lat = slice(5, -20), lon = slice(150, 170), time = (sst_anom['time.month']==3))
marchSST1 = marchdata1.sel(time = slice('1900-03-01', '2015-03-01'))
marchmean1 = (marchSST1*weights1).mean({'lon', 'lat'})/weights1.mean() 

aprildata1 = sst_anom.sel(lat = slice(5, -20), lon = slice(150, 170), time = (sst_anom['time.month']==4))
aprilSST1 = aprildata1.sel(time = slice('1900-04-01', '2015-04-01'))
aprilmean1 = (aprilSST1*weights1).mean({'lon', 'lat'})/weights1.mean() 

maydata1 = sst_anom.sel(lat = slice(5, -20), lon = slice(150, 170), time = (sst_anom['time.month']==5))
maySST1 = maydata1.sel(time = slice('1900-05-01', '2015-05-01'))
maymean1 = (maySST1*weights1).mean({'lon', 'lat'})/weights1.mean()

marchmean1.time.data = maymean1.time.data
aprilmean1.time.data = maymean1.time.data
DSST1mean = (maymean1 + aprilmean1 + marchmean1)/3

#DSST2
latrange2 = sst_anom.sel(lat = slice(10, -10)).lat
weights2 = np.cos(latrange2*np.pi/180)

marchdata2 = sst_anom.sel(lat = slice(10, -10), lon = slice(250, 280), time = (sst_anom['time.month']==3))
marchSST2 = marchdata2.sel(time = slice('1900-03-01', '2015-03-01'))
marchmean2 = (marchSST2*weights2).mean({'lon', 'lat'})/weights2.mean()

aprildata2 = sst_anom.sel(lat = slice(10, -10), lon = slice(250, 280), time = (sst_anom['time.month']==4))
aprilSST2 = aprildata2.sel(time = slice('1900-04-01', '2015-04-01'))
aprilmean2 = (aprilSST2*weights2).mean({'lon', 'lat'})/weights2.mean() 

maydata2 = sst_anom.sel(lat = slice(10, -10), lon = slice(250, 280), time = (sst_anom['time.month']==5))
maySST2 = maydata2.sel(time = slice('1900-05-01', '2015-05-01'))
maymean2 = (maySST2*weights2).mean({'lon', 'lat'})/weights2.mean()

marchmean2.time.data = maymean2.time.data
aprilmean2.time.data = maymean2.time.data
DSST2mean = (maymean2 + aprilmean2 + marchmean2)/3

EPToriginalmean = DSST1mean - DSST2mean
#print(EPToriginalmean)
EPTstd = EPToriginalmean.std()
EPTmean = EPToriginalmean.mean()
EPToriginalmean = (EPToriginalmean - EPTmean)/EPTstd
print(EPToriginalmean)

<xarray.DataArray (time: 88)>
array([-1.001022e+00,  4.092521e-01, -8.242461e-02, -3.950637e-01,
       -1.991887e+00, -5.299378e-01,  1.560524e+00,  9.171774e-01,
        1.861798e+00,  7.184782e-01,  5.132719e-01, -1.393943e+00,
        6.510655e-01, -8.583212e-01, -1.542083e+00, -5.391475e-01,
        7.739933e-01, -1.586646e-01,  2.022947e+00, -1.050585e+00,
       -9.153548e-01, -3.219801e-01, -3.372386e-01, -2.678311e-01,
       -1.133814e+00, -3.801206e-01,  2.781658e-01, -1.719525e-01,
       -6.795717e-01,  1.400972e+00, -8.641061e-01, -2.277115e+00,
        3.372310e-01,  6.574911e-01,  1.270842e-02,  3.108336e-01,
        1.808633e+00,  6.328033e-01, -1.012164e+00, -1.072956e-01,
       -6.848660e-01, -1.839094e+00,  1.232946e+00,  4.221162e-01,
       -1.384519e+00, -1.189353e+00,  1.413989e+00, -1.641494e+00,
        4.898613e-01,  1.438546e+00, -1.031586e+00,  9.106532e-01,
        8.513597e-01,  5.350164e-01,  3.352629e-01,  4.771452e-01,
       -1.099682e-02,  7.402413e

In [151]:
DSST1 = (maymean1 - marchmean1)
DSST2 = (maymean2 - marchmean2)

EPToriginal = DSST1 - DSST2
#print(EPToriginal)
EPTstd = EPToriginal.std()
EPTmean = EPToriginal.mean()
EPToriginal = (EPToriginal - EPTmean)/EPTstd
print(EPToriginal)

<xarray.DataArray (time: 88)>
array([-0.080772, -0.225218,  0.491362, -1.248134, -0.645189,  1.300251,
        0.555063, -0.063452,  0.173578, -1.033324,  0.176229, -0.491122,
        0.298478, -0.402067, -0.491007,  0.679845, -0.333592, -0.454124,
        0.117195,  0.033229,  0.077323, -0.115866, -0.46666 , -0.496127,
        0.802483,  0.054825, -0.874542, -0.059067,  0.281781,  0.477808,
       -0.82264 , -0.136874,  1.136438, -0.28846 ,  0.035331, -0.42295 ,
       -0.066865,  0.939073,  1.160478, -0.305911,  0.670286, -0.268746,
        0.992416,  0.256889, -0.598241, -0.291915,  1.099309, -0.964797,
       -0.225345, -0.172757, -0.461868,  0.029544, -0.040109,  0.552491,
       -0.469256,  0.50869 , -0.507958,  0.363192, -0.664474,  0.205008,
       -0.462678,  0.378158,  0.317906,  0.277455, -0.084356,  0.401585,
        0.088779, -0.242947, -0.210495, -0.623765, -0.269915,  0.539811,
        0.317138, -1.218497,  0.403829, -0.35236 ,  0.11463 ,  0.386073,
        0.341404, -0.

In [152]:
#EPT new
#(10s-10n, 130-80w)
#(10s-20n, 120-155e)

#DSST!
latrange1 = sst_anom.sel(lat = slice(20, -10)).lat
weights1 = np.cos(latrange1*np.pi/180)

marchdata1 = sst_anom.sel(lat = slice(20, -10), lon = slice(120, 155), time = (sst_anom['time.month']==3))
marchSST1 = marchdata1.sel(time = slice('1900-03-01', '2015-03-01'))
marchmean1 = (marchSST1*weights1).mean({'lon', 'lat'})/weights1.mean()

aprildata1 = sst_anom.sel(lat = slice(20, -10), lon = slice(120, 155), time = (sst_anom['time.month']==4))
aprilSST1 = aprildata1.sel(time = slice('1900-04-01', '2015-04-01'))
aprilmean1 = (aprilSST1*weights1).mean({'lon', 'lat'})/weights1.mean() 

maydata1 = sst_anom.sel(lat = slice(20, -10), lon = slice(120, 155), time = (sst_anom['time.month']==5))
maySST1 = maydata1.sel(time = slice('1900-05-01', '2015-05-01'))
maymean1 = (maySST1*weights1).mean({'lon', 'lat'})/weights1.mean()

marchmean1.time.data = maymean1.time.data
aprilmean1.time.data = maymean1.time.data
DSST1new = (maymean1 + aprilmean1 + marchmean1)/3

#DSST2
latrange2 = sst_anom.sel(lat = slice(10, -10)).lat
weights2 = np.cos(latrange2*np.pi/180)

marchdata2 = sst_anom.sel(lat = slice(10, -10), lon = slice(230, 280), time = (sst_anom['time.month']==3))
marchSST2 = marchdata2.sel(time = slice('1900-03-01', '2015-03-01'))
marchmean2 = (marchSST2*weights2).mean({'lon', 'lat'})/weights2.mean() 

aprildata2 = sst_anom.sel(lat = slice(10, -10), lon = slice(230, 280), time = (sst_anom['time.month']==4))
aprilSST2 = aprildata2.sel(time = slice('1900-04-01', '2015-04-01'))
aprilmean2 = (aprilSST2*weights2).mean({'lon', 'lat'})/weights2.mean() 

maydata2 = sst_anom.sel(lat = slice(10, -10), lon = slice(230, 280), time = (sst_anom['time.month']==5))
maySST2 = maydata2.sel(time = slice('1900-05-01', '2015-05-01'))
maymean2 = (maySST2*weights2).mean({'lon', 'lat'})/weights2.mean()

marchmean2.time.data = maymean2.time.data
aprilmean2.time.data = maymean2.time.data
DSST2new = (maymean2 + aprilmean2 + marchmean2)/3

EPT = DSST1new - DSST2new
#print(EPT)
EPTstd = EPT.std()
EPTmean = EPT.mean()
EPT = (EPT - EPTmean)/EPTstd
print(EPT)

<xarray.DataArray (time: 88)>
array([-0.478318, -0.03203 , -0.200174, -0.085164, -1.184418, -0.303983,
        0.671755,  0.593781,  1.207459,  0.479669,  0.102279, -0.760956,
        0.272604,  0.417922, -0.554319, -0.447154,  0.880621, -0.279734,
        0.571683, -0.1461  , -0.598452,  0.233263, -0.312774, -0.51441 ,
       -0.689699,  0.03529 ,  0.058239, -0.111712, -0.191724,  0.819269,
       -0.100841, -1.07182 , -0.128942,  0.185436, -0.470774,  0.397612,
        1.007612,  0.119835, -0.350705, -0.122547, -0.287524, -0.575647,
        0.822414,  0.490268, -0.690308, -0.752628,  0.79217 , -0.678447,
        0.00836 ,  0.551998, -0.612676,  0.337533,  0.570257,  0.092181,
        0.108381,  0.394022, -0.031021,  0.350358, -0.263635,  0.279484,
       -0.29115 ,  0.12391 ,  0.658419,  0.317342, -0.963306,  0.507694,
        0.614481, -0.059461, -0.368765, -1.122994,  0.249063,  0.100838,
        0.540123, -0.631682, -1.766879,  0.42539 ,  0.405959, -0.035926,
        0.335231,  0.

In [153]:
eptoriginal_subtraction = correlation(EPToriginal, precipa_jjas, dims='time')
print("EPT Original", eptoriginal_subtraction.data)
ept_australia = correlation(DSST1, precipa_jjas, dims='time')
print("DSST1", ept_australia.data)
ept_pacific = correlation(DSST2, precipa_jjas, dims='time')
print("DSST2", ept_pacific.data)

print()
eptoriginalmean_subtraction = correlation(EPToriginalmean, precipa_jjas, dims='time')
print("EPT Original Mean", eptoriginalmean_subtraction.data)
ept_australiamean = correlation(DSST1mean, precipa_jjas, dims='time')
print("DSST1", ept_australiamean.data)
ept_pacificmean = correlation(DSST2mean, precipa_jjas, dims='time')
print("DSST2", ept_pacificmean.data)

print()
ept_subtraction = correlation(EPT, precipa_jjas, dims='time')
print("New EPT", ept_subtraction.data)
ept_australianew = correlation(DSST1new, precipa_jjas, dims='time')
print("DSST1 New", ept_australianew.data)
ept_pacificnew = correlation(DSST2new, precipa_jjas, dims='time')
print("DSST2 New", ept_pacificnew.data)

EPT Original 0.4090731070587664
DSST1 0.12665884513888592
DSST2 -0.4011344478256808

EPT Original Mean 0.31994607004780984
DSST1 0.012677069713211699
DSST2 -0.32672332406453375

New EPT 0.37135127455627887
DSST1 New 0.10499425764968058
DSST2 New -0.3028914065363354


# CPT

In [166]:
#CP-ENSOpredictor

#DSST1
latrange1 = sst_anom.sel(lat = slice(-10, -25)).lat
weights1 = np.cos(latrange1*np.pi/180)

aprildata1 = sst_anom.sel(lat = slice(-10, -25), lon = slice(170, 200), time = (sst_anom['time.month']==4))
aprilSST1 = aprildata1.sel(time = slice('1900-04-01', '2015-04-01'))
aprilmean1 = (aprilSST1*weights1).mean({'lon', 'lat'})/weights1.mean()

maydata1 = sst_anom.sel(lat = slice(-10, -25), lon = slice(170, 200), time = (sst_anom['time.month']==5))
maySST1 = maydata1.sel(time = slice('1900-05-01', '2015-05-01'))
maymean1 = (maySST1*weights1).mean({'lon', 'lat'})/weights1.mean()

aprilmean1.time.data = maymean1.time.data
DSST1 = maymean1 - aprilmean1

#DSST2
latrange2 = sst_anom.sel(lat = slice(20, 5)).lat
weights2 = np.cos(latrange2*np.pi/180)

aprildata2 = sst_anom.sel(lat = slice(20, 5), lon = slice(180, 210), time = (sst_anom['time.month']==4))
aprilSST2 = aprildata2.sel(time = slice('1900-04-01', '2015-04-01'))
aprilmean2 = (aprilSST2*weights2).mean({'lon', 'lat'})/weights2.mean()
                          
maydata2 = sst_anom.sel(lat = slice(20, 5), lon = slice(180, 210), time = (sst_anom['time.month']==5))
maySST2 = maydata2.sel(time = slice('1900-05-01', '2015-05-01'))
maymean2 = (maySST2*weights2).mean({'lon', 'lat'})/weights2.mean()
                          
aprilmean2.time.data = maymean2.time.data
DSST2 = maymean2 - aprilmean2

CPToriginal = DSST1 - DSST2
#print(CPToriginal)
CPTstd = CPToriginal.std()
CPTmean = CPToriginal.mean()
CPToriginal = (CPToriginal - CPTmean)/CPTstd
print(CPToriginal)

<xarray.DataArray (time: 88)>
array([ 1.034446, -1.644795,  0.260865, -1.523214, -2.058889,  0.279677,
        0.520603,  1.476613, -2.861686, -0.120737,  1.58951 , -0.388673,
       -0.027112,  2.047418,  0.3757  , -2.200316,  0.330586,  0.319994,
        0.059772, -0.089702,  0.473585,  0.404069, -0.20933 , -0.375415,
        0.049273, -0.243741,  0.289054, -0.338636, -0.127177,  0.813011,
        1.631568, -0.410525,  0.048517,  1.325921,  0.397832, -1.561584,
       -0.733634,  0.632544, -1.80833 , -2.158612,  0.166518, -0.548333,
        0.10629 ,  0.632596,  0.460435,  0.484698,  1.546964, -1.403212,
       -0.420896,  0.689404, -0.674952,  2.048375,  0.677564, -0.983772,
       -0.169912,  0.553684, -0.01093 ,  1.495744,  0.917114, -0.158445,
       -0.07368 , -1.074418, -0.567051, -0.620656, -1.619773, -0.047012,
        0.628906,  2.138351, -0.738455, -0.077431, -0.415636,  0.498731,
       -1.319567, -0.649522,  2.0164  , -1.059239, -0.481311, -0.565523,
        0.49364 ,  0.

In [167]:
#(55-5s, 175e-155w)
latrange1 = sst_anom.sel(lat = slice(-5, -55)).lat
weights1 = np.cos(latrange1*np.pi/180)

aprildata1 = sst_anom.sel(lat = slice(-5, -55), lon = slice(175, 205), time = (sst_anom['time.month']==4))
aprilSST1 = aprildata1.sel(time = slice('1900-04-01', '2015-04-01'))
aprilmean1 = (aprilSST1*weights1).mean({'lon', 'lat'})/weights1.mean()

maydata1 = sst_anom.sel(lat = slice(-5, -55), lon = slice(175, 205), time = (sst_anom['time.month']==5))
maySST1 = maydata1.sel(time = slice('1900-05-01', '2015-05-01'))
maymean1 = (maySST1*weights1).mean({'lon', 'lat'})/weights1.mean()

aprilmean1.time.data = maymean1.time.data
DSST1new = maymean1 - aprilmean1

CPT = DSST1new
CPTstd = CPT.std()
CPTmean = CPT.mean()
CPT = (CPT - CPTmean)/CPTstd
print(CPT)

<xarray.DataArray (time: 88)>
array([ 0.413217, -1.412964,  0.18862 , -2.425838, -3.147323, -1.376669,
       -0.267006,  0.612157, -0.192166, -0.676915,  0.821784, -1.016349,
        0.295765,  3.117042,  0.491891, -0.238895,  0.157547,  0.023138,
       -0.499815,  0.83123 ,  0.626021,  0.885561,  0.130674, -0.307108,
        1.194109,  0.664761, -0.931261, -1.636097, -0.591374, -0.533841,
        1.510118,  0.551406,  1.524788,  0.120483,  0.776971, -1.789856,
        1.148034,  0.173274, -0.014265, -0.10438 , -0.744044,  0.688941,
       -0.173456,  1.24826 ,  1.372423, -0.897227,  1.586309, -0.7768  ,
       -0.347138,  1.005534, -0.708128,  0.772665,  0.725804, -0.292203,
       -0.484095,  0.277428, -0.823857,  1.761318, -0.940902, -0.196139,
       -0.882469, -0.715752,  0.15835 , -1.34445 , -1.414678, -0.159447,
        0.913335,  1.914355, -0.691284,  0.222586, -0.113775, -0.125853,
       -1.123544, -1.491947,  0.978121,  0.060592,  0.453439, -1.429334,
        0.762192,  0.

In [170]:
cptoriginal_subtraction = correlation(CPToriginal, precipa_jjas, dims='time')
print("CPT Original", cptoriginal_subtraction.data)
cpt_southpacific = correlation(DSST1, precipa_jjas, dims='time')
print("DSST1", cpt_southpacific.data)
cpt_northpacific = correlation(DSST2, precipa_jjas, dims='time')
print("DSST2", cpt_northpacific.data)

print()
cptnew = correlation(CPT, precipa_jjas, dims='time')
print("CPT New", cptnew.data)
cpt_pacific = correlation(DSST1new, precipa_jjas, dims='time')
print("DSST", cpt_pacific.data)

CPT Original 0.30216343741904705
DSST1 0.3371017431515418
DSST2 -0.06835848663702536

CPT New 0.4316652726687996
DSST 0.4316652410638617


# PSH 1

In [219]:
#mega-ENSOpredictor

#NPcalculation
latrange1 = slp_anom.sel(lat = slice(-40, -10)).lat
weights1 = np.cos(latrange1*np.pi/180)

marchdata1 = slp_anom.sel(lat = slice(-40, -10), lon = slice(200, 270), time = (slp_anom['time.month']==3))
marchSLP1 = marchdata1.sel(time=slice('1900-03-01','2015-03-01'))
marchmean1 = ((marchSLP1*weights1).mean({'lon', 'lat'})/weights1.mean())

aprildata1 = slp_anom.sel(lat = slice(-40, -10), lon = slice(200, 270), time = (slp_anom['time.month']==4))
aprilSLP1 = aprildata1.sel(time=slice('1900-04-01','2015-04-01'))
aprilmean1 = ((aprilSLP1*weights1).mean({'lon', 'lat'})/weights1.mean())

maydata1 = slp_anom.sel(lat = slice(-40, -10), lon = slice(200, 270), time = (slp_anom['time.month']==5))
maySLP1 = maydata1.sel(time = slice('1900-05-01', '2015-05-01'))
maymean1 = ((maySLP1*weights1).mean({'lon', 'lat'})/weights1.mean())

marchmean1.time.data = maymean1.time.data
aprilmean1.time.data = maymean1.time.data
NP = ((aprilmean1 + maymean1)/2)

#SPcalculation
latrange2 = slp_anom.sel(lat = slice(10, 30)).lat
weights2 = np.cos(latrange2*np.pi/180)

marchdata2 = slp_anom.sel(lat = slice(10, 30), lon = slice(180, 230), time = (slp_anom['time.month']==3))
marchSLP2 = marchdata2.sel(time = slice('1900-03-01', '2015-03-01'))
marchmean2 = ((marchSLP2*weights2).mean({'lon', 'lat'})/weights2.mean())

aprildata2 = slp_anom.sel(lat = slice(10, 30), lon = slice(180, 230), time = (slp_anom['time.month']==4))
aprilSLP2 = aprildata2.sel(time = slice('1900-04-01', '2015-04-01'))
aprilmean2 = ((aprilSLP2*weights2).mean({'lon', 'lat'})/weights2.mean())

maydata2 = slp_anom.sel(lat = slice(10, 30), lon = slice(180, 230), time = (slp_anom['time.month']==5))
maySLP2 = maydata2.sel(time = slice('1900-05-01', '2015-05-01'))
maymean2 = ((maySLP2*weights2).mean({'lon', 'lat'})/weights2.mean())

marchmean2.time.data = maymean2.time.data
aprilmean2.time.data = maymean2.time.data
SP = ((aprilmean2 + maymean2)/2)

NParea = (30*weights1.mean() * 60)
SParea = (20*weights2.mean() * 50)
PSHoriginal = ((NP * NParea) + (SP * SParea))/(NParea + SParea)
#print(PSHoriginal)
PSHstd = PSHoriginal.std()
PSHmean = PSHoriginal.mean()
PSHoriginal = (PSHoriginal - PSHmean)/PSHstd
print(PSHoriginal)

<xarray.DataArray (time: 88)>
array([-0.160115, -0.530665, -0.587413, -1.843401, -1.788555, -1.270153,
       -2.416847, -0.284868, -1.137765, -1.446228, -1.358026, -2.107617,
       -1.960992,  0.310206, -0.602675, -2.043644, -0.989641, -0.354539,
       -0.568459, -0.210822, -0.243621, -0.166101, -0.30196 , -0.897021,
       -0.68801 ,  0.004897, -0.919351,  0.050459,  0.106954,  1.509064,
       -0.682947,  0.842869,  0.474949, -0.310772,  0.77388 ,  0.451246,
        0.194778, -0.114258, -0.790516, -1.199903, -0.141202, -0.073532,
       -0.353318,  1.469441, -0.647314, -0.674508,  0.623298, -0.009869,
        0.248863, -0.547945, -0.071907,  0.794849,  0.612015,  0.191663,
        0.773995,  0.775393,  0.721223,  0.129456, -0.687075, -0.052964,
       -0.759927,  1.620226,  0.787352, -0.460351,  0.997016,  1.367667,
        0.402568,  0.874843, -0.273629,  0.244379,  0.340428,  0.495529,
        1.741729, -1.281774,  1.695221,  2.256278,  1.732105, -0.113447,
        1.202087,  0.

In [229]:
NPmam = ((marchmean1 + aprilmean1 + maymean1)/3)
SPmam = ((marchmean2 + aprilmean2 + maymean2)/3)

PSHmam = ((NPmam * NParea) + (SPmam * SParea))/(NParea + SParea)
PSHstd = PSHmam.std()
PSHmean = PSHmam.mean()
PSHmam = (PSHmam - PSHmean)/PSHstd
print(PSHmam)

<xarray.DataArray (time: 88)>
array([-6.831179e-01, -5.999682e-01, -1.160209e+00, -1.537893e+00,
       -2.215940e+00, -1.213828e+00, -3.045280e+00, -4.760478e-01,
       -9.106184e-01, -1.753336e+00, -9.360720e-01, -2.028238e+00,
       -2.392695e+00,  3.682125e-01, -8.874249e-01, -1.644145e+00,
       -7.992874e-01, -6.267059e-01, -4.443489e-01, -7.948714e-01,
       -6.456407e-01,  4.098698e-01, -2.110797e-01, -8.572396e-01,
       -4.771991e-01, -2.455378e-01, -8.047355e-01,  9.867723e-02,
       -5.624620e-02,  1.334306e+00, -6.853132e-01,  5.835380e-01,
        6.244053e-01, -7.223991e-01,  2.852268e-01,  8.773341e-01,
        2.658506e-01, -2.050980e-03, -6.964100e-01, -1.391489e+00,
        9.351112e-02,  4.056264e-02, -5.779046e-01,  1.078164e+00,
       -3.805864e-01, -6.138678e-01,  1.062420e+00, -1.212729e-01,
        2.888503e-01,  3.206597e-01,  1.283043e-01,  6.662065e-01,
        7.779165e-01,  7.036594e-01,  9.616296e-01,  1.182424e+00,
        7.116171e-01,  4.992048e

In [230]:
pshoriginal_subtraction = correlation(PSHoriginal, precipa_jjas, dims='time')
print("PSH Original", pshoriginal_subtraction.data)
psh_northpacific = correlation(NP, precipa_jjas, dims='time')
print("NP", psh_northpacific.data)
psh_southpacific = correlation(SP, precipa_jjas, dims='time')
print("SP", psh_southpacific.data)

print()
pshmam_subtraction = correlation(PSHmam, precipa_jjas, dims='time')
print("PSH MAM", pshmam_subtraction.data)
pshmam_northpacific = correlation(NPmam, precipa_jjas, dims='time')
print("NP MAM", pshmam_northpacific.data)
pshmam_southpacific = correlation(SPmam, precipa_jjas, dims='time')
print("SP MAM", pshmam_southpacific.data)

PSH Original 0.2511766012836855
NP 0.212805324180741
SP 0.21882287006708628

PSH MAM 0.26171068608745524
NP MAM 0.23816789300643842
SP MAM 0.20010652961195954


# PSH 2